services:
  app:
    image: ghcr.io/solivioai/solivio-app:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: apps/solivio/Dockerfile
      target: runner
      cache_from:
        - ghcr.io/solivioai/solivio-app:latest

  db-push:
    image: ghcr.io/solivioai/solivio-db-push:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: apps/solivio/Dockerfile
      target: db-push
      cache_from:
        - ghcr.io/solivioai/solivio-db-push:latest
