import fs from "node:fs";
import path from "node:path";

const TS_HEADER = "// @generated by `yarn generate` — DO NOT EDIT.\n";
const CSS_HEADER = "/* @generated by `yarn generate` — DO NOT EDIT. */\n";

export function headerFor(filePath: string): string {
  if (filePath.endsWith(".css")) return CSS_HEADER;
  if (filePath.endsWith(".json")) return "";
  return TS_HEADER;
}

/**
 * Deterministic writer for generator-owned trees: writes files only when
 * content changed (keeps dev watchers calm) and prunes files it did not
 * produce on this run.
 */
export class Writer {
  private written = new Set<string>();
  private changed = 0;

  constructor(private readonly repoRoot: string) {}

  /** Write a file (path relative to the repo root), prefixing the @generated header. */
  write(relPath: string, content: string): void {
    const absPath = path.join(this.repoRoot, relPath);
    const finalContent = headerFor(absPath) + content;
    this.written.add(absPath);
    if (fs.existsSync(absPath) && fs.readFileSync(absPath, "utf8") === finalContent) {
      return;
    }
    fs.mkdirSync(path.dirname(absPath), { recursive: true });
    fs.writeFileSync(absPath, finalContent);
    this.changed += 1;
  }

  /** Remove files under an owned tree (relative to repo root) that this run did not write. */
  prune(relTree: string): void {
    const absTree = path.join(this.repoRoot, relTree);
    if (!fs.existsSync(absTree)) return;
    const walk = (dir: string): void => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const absPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          walk(absPath);
          if (fs.readdirSync(absPath).length === 0) fs.rmdirSync(absPath);
        } else if (!this.written.has(absPath)) {
          fs.rmSync(absPath);
          this.changed += 1;
        }
      }
    };
    walk(absTree);
  }

  get changedCount(): number {
    return this.changed;
  }
}
