/**
 * Write DTO for a canonical product — the shape modules must produce
 * when importing products into the core.
 *
 * Excludes fields the core generates on save:
 * - `id`               — generated by the database
 * - `createdAt`        — generated by the database
 * - `combinedEmbedding` — generated by the core's embedding service
 *
 * `sku` is the stable external identifier used for upserts.
 */
export interface ProductInput {
  sku: string;
  name: string;
  description: string;
  priceNet: number;
  /** Gross price. If omitted the core derives it from priceNet + vatRate. */
  priceGross?: number;
  /** VAT rate as a decimal percentage, e.g. 23 for 23%. Defaults to 0. */
  vatRate?: number;
  currency: string;
}
