/**
 * Write DTO for a canonical product — the shape modules must produce
 * when importing products into the core.
 *
 * Excludes fields the core generates on save:
 * - `id`               — generated by the database
 * - `createdAt`        — generated by the database
 * - `embedding`        — generated by the core's embedding service
 *
 * `sku` is the stable external identifier used for upserts.
 */
export interface ProductInput {
  sku: string;
  name: string;
  description: string;
  /** Net price. */
  priceNet: number;
  /** Gross price. */
  priceGross: number;
  /** VAT rate as a decimal percentage, e.g. 23 for 23%. */
  vatRate: number;
  currency: string;
}
